
spring:
  activemq:
    broker-url: "localhost:15672"
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/moezboukhari/spring-cloud-config.git
          clone-on-start: true
          search-paths:
          - "{application}"
eureka:
  client:
    service-url:
      default-zone: "http/localhost:8761/eureka/"
    enabled: true
    registry-fetch-interval-seconds:  10
    instance-info-replication-interval-seconds: 20
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
server:
  port: 8888


